# Config globale pour tous les microservices

# Eureka - commun à tous
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator - commun à tous
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
# Logging - commun à tous
logging.level.root=INFO
logging.level.com.banque=DEBUG
