# Config globale pour tous les microservices
# Configuration PostgreSQL GLOBALE (partagée)
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA GLOBALE (partagée)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Eureka - commun à tous
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator - commun à tous
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
# Logging - commun à tous
logging.level.root=INFO
logging.level.com.banque=DEBUG

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method